# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Build types
        run: |
          yarn install --frozen-lockfile
          yarn pack:type

      - name: Publish types lib
        uses: JS-DevTools/npm-publish@v2
        with:
          package: "packages/types"
          token: ${{ secrets.types_lib_token }}
          access: public
